name: Deploy application
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16'
    - name: Install packages
      run: yarn install --frozen-lockfile
    - name: Build application
      run: yarn build
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
        force_orphan: true